/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "timer.h"
#include "led.h"






int main(void)
{

	led_init();
	timer_ini();
	timer_start();
    /* Loop forever */
	while(1)
	{
		//check if the interrupt on

					bool temp = timer_check();
					if(temp)
					{
						led_toggle();

					}
	}
}
